name: Validate PR
on:
  pull_request:
    branches:
      - 'master'
jobs:
  build_project:
    runs-on: macos-latest
    env:
      GITHUB_USER: ${{ secrets.USER }}
      GITHUB_API_KEY: ${{ secrets.PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: |
          ./gradlew :in-app-review-kmp:build --no-daemon